Make sure dependency installation completes before checking for phinx

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -84,17 +84,11 @@ if [ $? -gt 0 ]; then
 		exit 1
 	fi
 fi
-# Check phinx
-if [[ ! -f "$phinx" && "$migrate" = true ]]; then
-	echo "!!! Migration tool phinx not installed, unable to run migrations"
-	exit 1
-fi
 
 # Disable interactive questions
 if [ "$nointeraction" = true ]; then
 	echo ">>> Disable interactive questions"
 	composer="$composer --no-interaction"
-	phinx="$phinx --no-interaction"
 fi
 
 # Deployment mode, disable all developer dependencies :)
@@ -111,6 +105,15 @@ else
 fi
 
 if [ "$migrate" = true ]; then
+	# Check phinx
+	if [ ! -f "$phinx" ]; then
+		echo "!!! Migration tool phinx not installed, unable to run migrations"
+		exit 1
+	fi
+	# Disable interactive questions
+	if [ "$nointeraction" = true ]; then
+		phinx="$phinx --no-interaction"
+	fi
 	echo ">>> Running migrations"
 	$phinx migrate -c application/phinx.php
 else
