Make bin/update work with local composer.phar, add "deploy" option, fixes T442

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -5,23 +5,38 @@ git pull
 git submodule sync
 git submodule update --init --recursive
 
-which composer >/dev/null 2>&1
+composer="composer"
+bower="bower"
+withdev=1
+
+which $composer >/dev/null 2>&1
 if [ $? -gt 0 ]; then
-	echo "!!! Missing the `composer` command, please install it: https://getcomposer.org/"
+	composer="./composer.phar"
+	if [ ! -f $composer ]; then
+		echo "!!! Missing the 'composer' command, please install it: https://getcomposer.org/"
+		exit 1
+	fi
+fi
+
+which $bower >/dev/null 2>&1
+if [ $? -gt 0 ]; then
+	echo "!!! Missing the 'bower' command, please install it: http://bower.io/"
 	exit 1
+fi
+
+# Deployment mode, disable all developer dependencies :)
+if [ -n "$1" -a "$1" == "deploy" ]; then
+	nodev=true
+	composer="$composer --no-dev"
+	bower="$bower --production"
 fi
 
 echo ">>> Updating server dependencies"
-[ -d vendor ] && composer update || composer install
-
-which bower >/dev/null 2>&1
-if [ $? -gt 0 ]; then
-	echo "!!! Missing the `bower` command, please install it: http://bower.io/"
-	exit 1
-fi
+[ -d vendor ] && $composer update || $composer install
+$composer dump-autoload
 
 echo ">>> Updating client dependencies"
-[ -d modules/UshahidiUI/media/bower_components ] && bower update || bower install
+[ -d modules/UshahidiUI/media/bower_components ] && $bower update || $bower install
 
 echo ">>> Running migrations"
 ./minion --task=migrations:run --up
