some bash fixes on bin/update, important for automation

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set +e    # soft fail to allow handling of php interpreter missing
+
 which php >/dev/null 2>&1
 if [ $? -eq 0 ]; then
 	php -r 'exit((int) version_compare(PHP_VERSION, "5.4", "<"));' >/dev/null 2>&1
@@ -8,6 +10,8 @@ if [ $? -eq 0 ]; then
 		exit 1
 	fi
 fi
+
+set -e    # hard fail to ensure the script exits with non-zero status when something fails
 
 # Defaults
 production=false
@@ -81,7 +85,7 @@ if [ $? -gt 0 ]; then
 	fi
 fi
 # Check phinx
-if [ -f "$phinx" && "$migrate" = true ]; then
+if [[ -f "$phinx" && "$migrate" = true ]]; then
 	echo "!!! Migration tool phinx not installed, unable to run migrations"
 	exit 1
 fi
